### ISSUE TITLE
color override does not seems to work

### ISSUE THREAD

**Issue by Thebarda** [metalelf0/black-metal-theme-neovim#7]
Hello, I'm trying to override some colors but even the code from the read me.
The fmt is working btw.

Is there something I can do?

![Image](https://github.com/user-attachments/assets/98ae8944-960f-4115-8ab3-8505ddd31153)

Thanks for the work 🤘

**Comment by fedya-eremin** [comment]
Same here

**Comment by metalelf0** [comment]
Hey, thanks for reporting. I'll check it ASAP  🤘

**Comment by M4rti21** [comment]
Hi, this seems to still be an issue 🥲

**Comment by metalelf0** [comment]
@M4rti21 @Thebarda @fedya-eremin this should be fixed, let me know!

**Comment by fedya-eremin** [comment]
never mind, I already implemented similar theme for personal usage) I think it's a good idea to use lush.nvim to give users an opportunity to customize theme at the end
if you are interested, github.com/fedya-eremin/nvim-colors

**Comment by jackddouglas** [comment]
hi! i've pulled the latest version of the plugin but color overrides still don't seem to work. i've included the relevant config below. as a side-note, the green and red diagnostics colors seem to be swapped. not sure if this is a stylistic choice, but i've noticed it across all the themes and ports (ghostty for instance).

```lua
{
    "metalelf0/black-metal-theme-neovim",
    lazy = false,
    priority = 1000,
    config = function()
      require("black-metal").setup({
        theme = "taake",
        colors = {
          diag_red = "#6e4c4c",
          diag_green = "#5f8787",
        },
      })
      require("black-metal").load()
    end,
  }
```

here i'm attempting to swap the existing colors for red and green diagnostics (and looking at gitsigns for changes, which is mapped correctly in the highlights logic).

i've also tried changing very obvious elements like the string color to bright magenta, also to no effect.

please let me know if i'm missing something, i couldn't spot faults in the plugin code. thanks!

**Comment by KarlHarnois** [comment]
Experiencing the same thing on my end. Seems to still be an issue.

**Comment by WinnerWind** [comment]
Thought i was going insane, but no i can't get it to work either. 
relevant config
```lua
return function()
	require("black-metal").setup({
		theme = "emperor",
		colors = {
			fg = "#f1f1f1",
			comment = "#e1e1e1",
			keyword = "#f1f1f1",
		},
	})
	require("black-metal").load()
end


```
loaded from a seperate file, but my `theme` setting is respected.

**Comment by metalelf0** [comment]
Hey, issue should now be fixed, can you folks please take a look and give me feedback?

**Comment by WinnerWind** [comment]
<img width="1191" height="542" alt="Image" src="https://github.com/user-attachments/assets/4b15870e-dd1f-4e3b-a73a-078655d6fe41" />
Seems to work!

**Comment by metalelf0** [comment]
@WinnerWind great, thanks for checking! I'll close the issue, feel free to reopen it if needed! 🤘🏻 Nice font btw :)

**Comment by WinnerWind** [comment]
Thanks! It's ProFont (I'm using the NerdFont version)!

Thank you for still maintaining these lovely themes!
